### ISSUE TITLE
Support for 3D CFD files

### ISSUE THREAD

**Issue by exook** [baler-collaboration/baler#37]
Implement a 3D convolutional neural network which can run on 3D time series CFD data

**Comment by singh96aman** [comment]
Could you please send a 3D CFD File to understand the work estimate ?
FYI, we'll have to make minor updates in all plots, with writing a new plot routine, I believe

**Comment by martacamps** [comment]
I've generated a 3D CFD field of a flow around a wall mounted cube. 

Here are some images of the flow: 

Vertical cut through the middle of the cube
![image](https://github.com/baler-collaboration/baler/assets/15945173/bad2b748-622e-4f8d-b4da-c9015a8dd181)

Horizontal cut through the middle of the cube
![image](https://github.com/baler-collaboration/baler/assets/15945173/c84b1bf7-91df-4c6e-84cc-d7177cf88dde)

The size of the file is 60 x 39 x 140 points. 60 in z direction, 39 in y direction and 140 in x direction. 

And this is a [link to the CFD data in .npz format](https://www.dropbox.com/s/qnybxdbmflpx6ws/3DCFD.npz?dl=0) with the data (3D array) and an empty 'names' array, as done for the other CFD data in Baler. 

Let me know if you need anything else, for example a different size of the data.

**Comment by singh96aman** [comment]
Few questions - @martacamps @exook 

1. This is a 60x39x140 dataset vs CFD flow datasets of 60x50x50. FYI I ran the Dense AE model on it and had to make few replacements. Not a question but a comment to make the Dense AE more generic.

2. Attached is the reconstruction plot from the Dense network. It does show reconstruction but differ from above Marta images so just want to confirm that the plot is working fine.

3. If above 2 points are fine, we can try the 3D Conv Net in #270 

![image](https://github.com/baler-collaboration/baler/assets/14856694/315039aa-3e76-4782-b6ab-e0f1f1c1fcae)

**Comment by martacamps** [comment]
Hi @singh96aman , thank you for working on the CFD branch, looks like good progress on the 3D CFD compression :-). 

2. The reconstruction plots look good, I think the image is the same as my top plot, just with a couple of differences: 
-  Different colour scale. 
-  Coordinates and flow velocity converted from lattice Boltzmann units to physical units. This simulation has different conversion values than the 60x50x50. The parameters for the 60x39x140 are: dt (time step) = 0.004; dx (cell size) = 0.05. I think there should be somewhere in the plotting script to enter this values, but they shouldn't really affect the quality of the compression. 

Also, the plot only shows one slice of the 3D flow. Showing 3D plots to include all the volume would be quite confusing though. One option would be to show an animation, as with the 60x50x50 case, but moving across the z coordinate instead of time. It could also be interesting to calculate the averaged error for all the cells, its minum, maximum etc.
